insert into concelhos (nome, slug, distrito) values
('Águeda','agueda','Aveiro'),
('Albergaria-a-Velha','albergaria-a-velha','Aveiro'),
('Anadia','anadia','Aveiro'),
('Arouca','arouca','Aveiro'),
('Aveiro','aveiro','Aveiro'),
('Castelo de Paiva','castelo-de-paiva','Aveiro'),
('Espinho','espinho','Aveiro'),
('Estarreja','estarreja','Aveiro'),
('Ílhavo','ilhavo','Aveiro'),
('Mealhada','mealhada','Aveiro'),
('Murtosa','murtosa','Aveiro'),
('Oliveira de Azeméis','oliveira-de-azemeis','Aveiro'),
('Oliveira do Bairro','oliveira-do-bairro','Aveiro'),
('Ovar','ovar','Aveiro'),
('Santa Maria da Feira','santa-maria-da-feira','Aveiro'),
('São João da Madeira','sao-joao-da-madeira','Aveiro'),
('Sever do Vouga','sever-do-vouga','Aveiro'),
('Vagos','vagos','Aveiro'),
('Vale de Cambra','vale-de-cambra','Aveiro'),
('Aljustrel','aljustrel','Beja'),
('Almodôvar','almodovar','Beja'),
('Alvito','alvito','Beja'),
('Barrancos','barrancos','Beja'),
('Beja','beja','Beja'),
('Castro Verde','castro-verde','Beja'),
('Cuba','cuba','Beja'),
('Ferreira do Alentejo','ferreira-do-alentejo','Beja'),
('Mértola','mertola','Beja'),
('Moura','moura','Beja'),
('Odemira','odemira','Beja'),
('Ourique','ourique','Beja'),
('Serpa','serpa','Beja'),
('Vidigueira','vidigueira','Beja'),
('Amares','amares','Braga'),
('Barcelos','barcelos','Braga'),
('Braga','braga','Braga'),
('Cabeceiras de Basto','cabeceiras-de-basto','Braga'),
('Celorico de Basto','celorico-de-basto','Braga'),
('Esposende','esposende','Braga'),
('Fafe','fafe','Braga'),
('Guimarães','guimaraes','Braga'),
('Póvoa de Lanhoso','povoa-de-lanhoso','Braga'),
('Terras de Bouro','terras-de-bouro','Braga'),
('Vieira do Minho','vieira-do-minho','Braga'),
('Vila Nova de Famalicão','vila-nova-de-famalicao','Braga'),
('Vila Verde','vila-verde','Braga'),
('Vizela','vizela','Braga'),
('Alfândega da Fé','alfandega-da-fe','Bragança'),
('Bragança','braganca','Bragança'),
('Carrazeda de Ansiães','carrazeda-de-ansiaes','Bragança'),
('Freixo de Espada à Cinta','freixo-de-espada-a-cinta','Bragança'),
('Macedo de Cavaleiros','macedo-de-cavaleiros','Bragança'),
('Miranda do Douro','miranda-do-douro','Bragança'),
('Mirandela','mirandela','Bragança'),
('Mogadouro','mogadouro','Bragança'),
('Torre de Moncorvo','torre-de-moncorvo','Bragança'),
('Vila Flor','vila-flor','Bragança'),
('Vimioso','vimioso','Bragança'),
('Vinhais','vinhais','Bragança'),
('Belmonte','belmonte','Castelo Branco'),
('Castelo Branco','castelo-branco','Castelo Branco'),
('Covilhã','covilha','Castelo Branco'),
('Fundão','fundao','Castelo Branco'),
('Idanha-a-Nova','idanha-a-nova','Castelo Branco'),
('Oleiros','oleiros','Castelo Branco'),
('Penamacor','penamacor','Castelo Branco'),
('Proença-a-Nova','proenca-a-nova','Castelo Branco'),
('Sertã','serta','Castelo Branco'),
('Vila de Rei','vila-de-rei','Castelo Branco'),
('Vila Velha de Ródão','vila-velha-de-rodao','Castelo Branco'),
('Arganil','arganil','Coimbra'),
('Cantanhede','cantanhede','Coimbra'),
('Coimbra','coimbra','Coimbra'),
('Condeixa-a-Nova','condeixa-a-nova','Coimbra'),
('Figueira da Foz','figueira-da-foz','Coimbra'),
('Góis','gois','Coimbra'),
('Lousã','lousa','Coimbra'),
('Mira','mira','Coimbra'),
('Miranda do Corvo','miranda-do-corvo','Coimbra'),
('Montemor-o-Velho','montemor-o-velho','Coimbra'),
('Oliveira do Hospital','oliveira-do-hospital','Coimbra'),
('Pampilhosa da Serra','pampilhosa-da-serra','Coimbra'),
('Penacova','penacova','Coimbra'),
('Penela','penela','Coimbra'),
('Soure','soure','Coimbra'),
('Tábua','tabua','Coimbra'),
('Vila Nova de Poiares','vila-nova-de-poiares','Coimbra'),
('Albufeira','albufeira','Faro'),
('Alcoutim','alcoutim','Faro'),
('Aljezur','aljezur','Faro'),
('Castro Marim','castro-marim','Faro'),
('Faro','faro','Faro'),
('Lagoa','lagoa','Faro'),
('Lagos','lagos','Faro'),
('Loulé','loule','Faro'),
('Monchique','monchique','Faro'),
('Olhão','olhao','Faro'),
('Portimão','portimao','Faro'),
('São Brás de Alportel','sao-bras-de-alportel','Faro'),
('Silves','silves','Faro'),
('Tavira','tavira','Faro'),
('Vila do Bispo','vila-do-bispo','Faro'),
('Vila Real de Santo António','vila-real-de-santo-antonio','Faro'),
('Aguiar da Beira','aguiar-da-beira','Guarda'),
('Almeida','almeida','Guarda'),
('Celorico da Beira','celorico-da-beira','Guarda'),
('Figueira de Castelo Rodrigo','figueira-de-castelo-rodrigo','Guarda'),
('Fornos de Algodres','fornos-de-algodres','Guarda'),
('Gouveia','gouveia','Guarda'),
('Guarda','guarda','Guarda'),
('Manteigas','manteigas','Guarda'),
('Mêda','meda','Guarda'),
('Pinhel','pinhel','Guarda'),
('Sabugal','sabugal','Guarda'),
('Seia','seia','Guarda'),
('Trancoso','trancoso','Guarda'),
('Vila Nova de Foz Côa','vila-nova-de-foz-coa','Guarda'),
('Lajes das Flores','lajes-das-flores','Açores'),
('Santa Cruz das Flores','santa-cruz-das-flores','Açores'),
('Angra do Heroísmo','angra-do-heroismo','Açores'),
('Praia da Vitória','praia-da-vitoria','Açores'),
('Santa Cruz da Graciosa','santa-cruz-da-graciosa','Açores'),
('Calheta','calheta','Madeira'),
('Câmara de Lobos','camara-de-lobos','Madeira'),
('Funchal','funchal','Madeira'),
('Machico','machico','Madeira'),
('Ponta do Sol','ponta-do-sol','Madeira'),
('Porto Moniz','porto-moniz','Madeira'),
('Ribeira Brava','ribeira-brava','Madeira'),
('Santa Cruz','santa-cruz','Madeira'),
('Santana','santana','Madeira'),
('São Vicente','sao-vicente','Madeira'),
('Porto Santo','porto-santo','Madeira'),
('Vila do Porto','vila-do-porto','Açores'),
('Calheta de São Jorge','calheta-de-sao-jorge','Açores'),
('Velas','velas','Açores'),
('Lagoa (Açores)','lagoa-acores','Açores'),
('Nordeste','nordeste','Açores'),
('Ponta Delgada','ponta-delgada','Açores'),
('Povoação','povoacao','Açores'),
('Ribeira Grande','ribeira-grande','Açores'),
('Vila Franca do Campo','vila-franca-do-campo','Açores'),
('Corvo','corvo','Açores'),
('Horta','horta','Açores'),
('Lajes do Pico','lajes-do-pico','Açores'),
('Madalena','madalena','Açores'),
('São Roque do Pico','sao-roque-do-pico','Açores'),
('Alcobaça','alcobaca','Leiria'),
('Alvaiázere','alvaiazere','Leiria'),
('Ansião','ansiao','Leiria'),
('Batalha','batalha','Leiria'),
('Bombarral','bombarral','Leiria'),
('Caldas da Rainha','caldas-da-rainha','Leiria'),
('Castanheira de Pêra','castanheira-de-pera','Leiria'),
('Figueiró dos Vinhos','figueiro-dos-vinhos','Leiria'),
('Leiria','leiria','Leiria'),
('Marinha Grande','marinha-grande','Leiria'),
('Nazaré','nazare','Leiria'),
('Óbidos','obidos','Leiria'),
('Pedrógão Grande','pedrogao-grande','Leiria'),
('Peniche','peniche','Leiria'),
('Pombal','pombal','Leiria'),
('Porto de Mós','porto-de-mos','Leiria'),
('Alenquer','alenquer','Lisboa'),
('Amadora','amadora','Lisboa'),
('Arruda dos Vinhos','arruda-dos-vinhos','Lisboa'),
('Azambuja','azambuja','Lisboa'),
('Cadaval','cadaval','Lisboa'),
('Cascais','cascais','Lisboa'),
('Lisboa','lisboa','Lisboa'),
('Loures','loures','Lisboa'),
('Lourinhã','lourinha','Lisboa'),
('Mafra','mafra','Lisboa'),
('Odivelas','odivelas','Lisboa'),
('Oeiras','oeiras','Lisboa'),
('Sintra','sintra','Lisboa'),
('Sobral de Monte Agraço','sobral-de-monte-agraco','Lisboa'),
('Torres Vedras','torres-vedras','Lisboa'),
('Vila Franca de Xira','vila-franca-de-xira','Lisboa'),
('Alter do Chão','alter-do-chao','Portalegre'),
('Arronches','arronches','Portalegre'),
('Avis','avis','Portalegre'),
('Campo Maior','campo-maior','Portalegre'),
('Castelo de Vide','castelo-de-vide','Portalegre'),
('Crato','crato','Portalegre'),
('Elvas','elvas','Portalegre'),
('Fronteira','fronteira','Portalegre'),
('Gavião','gaviao','Portalegre'),
('Marvão','marvao','Portalegre'),
('Monforte','monforte','Portalegre'),
('Nisa','nisa','Portalegre'),
('Ponte de Sor','ponte-de-sor','Portalegre'),
('Portalegre','portalegre','Portalegre'),
('Sousel','sousel','Portalegre'),
('Amarante','amarante','Porto'),
('Baião','baiao','Porto'),
('Felgueiras','felgueiras','Porto'),
('Gondomar','gondomar','Porto'),
('Lousada','lousada','Porto'),
('Maia','maia','Porto'),
('Marco de Canaveses','marco-de-canaveses','Porto'),
('Matosinhos','matosinhos','Porto'),
('Paços de Ferreira','pacos-de-ferreira','Porto'),
('Paredes','paredes','Porto'),
('Penafiel','penafiel','Porto'),
('Porto','porto','Porto'),
('Póvoa de Varzim','povoa-de-varzim','Porto'),
('Santo Tirso','santo-tirso','Porto'),
('Trofa','trofa','Porto'),
('Valongo','valongo','Porto'),
('Vila do Conde','vila-do-conde','Porto'),
('Vila Nova de Gaia','vila-nova-de-gaia','Porto'),
('Abrantes','abrantes','Santarém'),
('Alcanena','alcanena','Santarém'),
('Almeirim','almeirim','Santarém'),
('Alpiarça','alpiarca','Santarém'),
('Benavente','benavente','Santarém'),
('Cartaxo','cartaxo','Santarém'),
('Chamusca','chamusca','Santarém'),
('Constância','constancia','Santarém'),
('Coruche','coruche','Santarém'),
('Entroncamento','entroncamento','Santarém'),
('Ferreira do Zêzere','ferreira-do-zezere','Santarém'),
('Golegã','golega','Santarém'),
('Mação','macao','Santarém'),
('Ourém','ourem','Santarém'),
('Rio Maior','rio-maior','Santarém'),
('Salvaterra de Magos','salvaterra-de-magos','Santarém'),
('Santarém','santarem','Santarém'),
('Sardoal','sardoal','Santarém'),
('Tomar','tomar','Santarém'),
('Torres Novas','torres-novas','Santarém'),
('Vila Nova da Barquinha','vila-nova-da-barquinha','Santarém'),
('Alcácer do Sal','alcacer-do-sal','Setúbal'),
('Alcochete','alcochete','Setúbal'),
('Almada','almada','Setúbal'),
('Barreiro','barreiro','Setúbal'),
('Grândola','grandola','Setúbal'),
('Moita','moita','Setúbal'),
('Montijo','montijo','Setúbal'),
('Palmela','palmela','Setúbal'),
('Santiago do Cacém','santiago-do-cacem','Setúbal'),
('Seixal','seixal','Setúbal'),
('Sesimbra','sesimbra','Setúbal'),
('Setúbal','setubal','Setúbal'),
('Sines','sines','Setúbal'),
('Arcos de Valdevez','arcos-de-valdevez','Viana do Castelo'),
('Caminha','caminha','Viana do Castelo'),
('Melgaço','melgaco','Viana do Castelo'),
('Monção','moncao','Viana do Castelo'),
('Paredes de Coura','paredes-de-coura','Viana do Castelo'),
('Ponte da Barca','ponte-da-barca','Viana do Castelo'),
('Ponte de Lima','ponte-de-lima','Viana do Castelo'),
('Valença','valenca','Viana do Castelo'),
('Viana do Castelo','viana-do-castelo','Viana do Castelo'),
('Vila Nova de Cerveira','vila-nova-de-cerveira','Viana do Castelo'),
('Alijó','alijo','Vila Real'),
('Boticas','boticas','Vila Real'),
('Chaves','chaves','Vila Real'),
('Mesão Frio','mesao-frio','Vila Real'),
('Mondim de Basto','mondim-de-basto','Vila Real'),
('Montalegre','montalegre','Vila Real'),
('Murça','murca','Vila Real'),
('Peso da Régua','peso-da-regua','Vila Real'),
('Ribeira de Pena','ribeira-de-pena','Vila Real'),
('Sabrosa','sabrosa','Vila Real'),
('Santa Marta de Penaguião','santa-marta-de-penaguiao','Vila Real'),
('Valpaços','valpacos','Vila Real'),
('Vila Pouca de Aguiar','vila-pouca-de-aguiar','Vila Real'),
('Vila Real','vila-real','Vila Real'),
('Armamar','armamar','Viseu'),
('Carregal do Sal','carregal-do-sal','Viseu'),
('Castro Daire','castro-daire','Viseu'),
('Cinfães','cinfaes','Viseu'),
('Lamego','lamego','Viseu'),
('Mangualde','mangualde','Viseu'),
('Moimenta da Beira','moimenta-da-beira','Viseu'),
('Mortágua','mortagua','Viseu'),
('Nelas','nelas','Viseu'),
('Oliveira de Frades','oliveira-de-frades','Viseu'),
('Penalva do Castelo','penalva-do-castelo','Viseu'),
('Penedono','penedono','Viseu'),
('Resende','resende','Viseu'),
('Santa Comba Dão','santa-comba-dao','Viseu'),
('São João da Pesqueira','sao-joao-da-pesqueira','Viseu'),
('São Pedro do Sul','sao-pedro-do-sul','Viseu'),
('Sátão','satao','Viseu'),
('Sernancelhe','sernancelhe','Viseu'),
('Tabuaço','tabuaco','Viseu'),
('Tarouca','tarouca','Viseu'),
('Tondela','tondela','Viseu'),
('Vila Nova de Paiva','vila-nova-de-paiva','Viseu'),
('Viseu','viseu','Viseu'),
('Vouzela','vouzela','Viseu'),
('Alandroal','alandroal','Évora'),
('Arraiolos','arraiolos','Évora'),
('Borba','borba','Évora'),
('Estremoz','estremoz','Évora'),
('Évora','evora','Évora'),
('Montemor-o-Novo','montemor-o-novo','Évora'),
('Mora','mora','Évora'),
('Mourão','mourao','Évora'),
('Portel','portel','Évora'),
('Redondo','redondo','Évora'),
('Reguengos de Monsaraz','reguengos-de-monsaraz','Évora'),
('Vendas Novas','vendas-novas','Évora'),
('Viana do Alentejo','viana-do-alentejo','Évora'),
('Vila Viçosa','vila-vicosa','Évora')
on conflict (slug) do nothing;
